title: "Red Team Learning"
description: "My path to mastering C development and red team techniques"
baseurl: ""
url: "https://www.s1nk.net"

theme: jekyll-theme-midnight

markdown: kramdown
highlighter: rouge
